# Declaring and initializing variables on phyton

#Strings
leejongsuk = "oppa"
kokobop = "Aso"
darkie = "kaklase nyong..."


#Numerical values
bilang_ng_oppa = 500
bilangNgOppa = 1000
kaligayahan = 0.5

print(leejongsuk)
print(kokobop)
print(darkie)


print(bilang_ng_oppa)
print(bilangNgOppa)
print(kaligayahan)

# Arithmetic
addition = 1 + 1
subtraction = 1 -1
division = 1/1
multiplication = 1 * 1
modulus = 5 % 3

print(addition)
print(subtraction)
print(division)
print(multiplication)
print(modulus)

if addition > division:
    print("Hello")
   elif modulus < multiplication
else:
    print("Hi")
